# -*- coding: utf-8 -*-
"""prathimad qqq leaps strategy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16MC2-SSfI4OP7NurO6nZsB-w6g8WfCx9

# Alpaca-py options trading basic

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/alpacahq/alpaca-py/blob/master/examples/options/options-trading-basic.ipynb)

- This notebook shows how to use alpaca-py with options trading API endpoints
- Please use ``paper account``. Please ``DO NOT`` use this notebook with live account. In this notebook, we place orders for options as an example.

# Setup
"""

# Please change the following to your own PAPER api key and secret
# or set them as environment variables (ALPACA_API_KEY, ALPACA_SECRET_KEY).
# You can get them from https://alpaca.markets/

api_key = ''
secret_key = ''

#### We use paper environment for this example ####
paper = True # Please do not modify this. This example is for paper trading only.
####

# Below are the variables for development this documents
# Please do not change these variables

trade_api_url = None
trade_api_wss = None
data_api_url = None
option_stream_data_wss = None

import alpaca

import os, json, time
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from alpaca.trading.client import TradingClient
from alpaca.data.timeframe import TimeFrame, TimeFrameUnit
from alpaca.data.historical.option import OptionHistoricalDataClient
from alpaca.trading.stream import TradingStream
from alpaca.data.live.option import OptionDataStream
from alpaca.data.historical.corporate_actions import CorporateActionsClient
from alpaca.data.historical.stock import StockHistoricalDataClient
from alpaca.data.live.stock import StockDataStream

from alpaca.data.requests import (
    OptionBarsRequest,
    OptionTradesRequest,
    OptionLatestQuoteRequest,
    OptionLatestTradeRequest,
    OptionSnapshotRequest,
    OptionChainRequest,

    CorporateActionsRequest,
    StockBarsRequest,
    StockQuotesRequest,
    StockTradesRequest,
    StockLatestTradeRequest,
)
from alpaca.trading.requests import (
    GetOptionContractsRequest,
    GetAssetsRequest,
    MarketOrderRequest,
    GetOrdersRequest,
    ClosePositionRequest,

    LimitOrderRequest,
    StopLimitOrderRequest,
    StopLossRequest,
    StopOrderRequest,
    TakeProfitRequest,
    TrailingStopOrderRequest,
)
from alpaca.trading.enums import (
    AssetStatus,
    ExerciseStyle,
    OrderSide,
    OrderType,
    TimeInForce,
    QueryOrderStatus,

    AssetExchange,
    AssetClass,
    OrderClass,
)
from alpaca.common.exceptions import APIError

if api_key is None:
    api_key = os.environ.get('ALPACA_API_KEY')

if secret_key is None:
    secret_key = os.environ.get('ALPACA_SECRET_KEY')

# to run async code in jupyter notebook
import nest_asyncio
nest_asyncio.apply()

# check version of alpaca-py
alpaca.__version__

"""# Helper Functions(No Execution)"""

# setup clients
trade_client = TradingClient(api_key=api_key, secret_key=secret_key, paper=paper, url_override=trade_api_url)
data_client = StockHistoricalDataClient(api_key=api_key, secret_key=secret_key)


# check trading account
# There are trhee new columns in the account object:
# - options_buying_power
# - options_approved_level
# - options_trading_level
acct = trade_client.get_account()

# check account configuration
# - we have new field `max_options_trading_level`
acct_config = trade_client.get_account_configurations()

def get_latest_price(symbol):
    """
    Fetches the latest trade price for a given stock symbol.
    """

    # 1. Build the request object for the provided symbol
    request_params = StockLatestTradeRequest(symbol_or_symbols=[symbol])

    # 2. Fetch the latest trade data
    latest_trade = data_client.get_stock_latest_trade(request_params)

    # 3. Extract and return the price value
    #display(latest_trade)
    return latest_trade[symbol].price

def select_high_interest_call_leap(symbol):
    # specify expiration date range
    now = datetime.now(tz = ZoneInfo("America/New_York"))
    day300 = now + timedelta(days = 300)
    day400 = now + timedelta(days = 400)

    latest_price = get_latest_price(symbol)
    # 1. Calculate the 1% lower boundary
    # We use round() to ensure standard strike price formatting
    min_strike = round(latest_price * 0.99, 2)
    max_strike = round(latest_price * 1.01, 2) # Optional: if you want a strict 1% ceiling


    req = GetOptionContractsRequest(
          underlying_symbols = [symbol],                     # specify underlying symbols
          status = AssetStatus.ACTIVE,                                 # specify asset status: active (default)
          expiration_date = None,                                      # specify expiration date (specified date + 1 day range)
          expiration_date_gte = day300.strftime(format = "%Y-%m-%d"),                           # we can pass date object
          expiration_date_lte = day400.strftime(format = "%Y-%m-%d"),   # or string
          root_symbol = None,                                          # specify root symbol
          type = "call",                                                # specify option type: put
          style = ExerciseStyle.AMERICAN,                              # specify option style: american
          strike_price_gte = str(min_strike),                     # specify strike price range
          strike_price_lte = str(max_strike),                     # specify strike price range
          limit = 100,                                                 # specify limit
          page_token = None,                                          # specify page
      )
    res = trade_client.get_option_contracts(req)
    selected_contract = max(res.option_contracts, key=lambda c: int(c.open_interest))

    if res.next_page_token is not None:
      req = GetOptionContractsRequest(
          underlying_symbols = [symbol],                     # specify underlying symbols
          status = AssetStatus.ACTIVE,                                 # specify asset status: active (default)
          expiration_date = None,                                      # specify expiration date (specified date + 1 day range)
          expiration_date_gte = day300.strftime(format = "%Y-%m-%d"),                           # we can pass date object
          expiration_date_lte = day400.strftime(format = "%Y-%m-%d"),   # or string
          root_symbol = None,                                          # specify root symbol
          type = "call",                                                # specify option type: put
          style = ExerciseStyle.AMERICAN,                              # specify option style: american
          strike_price_gte = str(min_strike),                                       # specify strike price range
          strike_price_lte = str(max_strike),                                   # specify strike price range
          limit = 100,                                                 # specify limit
          page_token = res.next_page_token,                                           # specify page
      )
      res = trade_client.get_option_contracts(req)
      selected_contract = max(selected_contract,
                              max(res.option_contracts, key=lambda c: int(c.open_interest)),
                              key=lambda obj: int(obj.open_interest))
      #display(res)

    #display(selected_contract)
    return selected_contract

def place_order_with_exit_at_50pct_profit(selected_contract):
    # place buy put option order
    # - we can place buy put option order same as buy stock/crypto order
    place_order_req = MarketOrderRequest(
        symbol = selected_contract.symbol,
        qty = 1,
        side = OrderSide.BUY,
        type = OrderType.MARKET,
        time_in_force = TimeInForce.DAY,
    )
    place_order_res = trade_client.submit_order(place_order_req)


    # 2. Wait for the order  to fill to get the true execution price
    # (Using a simple while loop here to check the status every 1 second)
    filled_order = trade_client.get_order_by_id(place_order_res.id)
    while filled_order.status.name != 'FILLED':
        time.sleep(1)
        filled_order = trade_client.get_order_by_id(place_order_res.id)

    # 3. Calculate the 50% profit target
    actual_fill_price = float(filled_order.filled_avg_price)
    target_price = round(actual_fill_price * 1.5, 2)

    print(f"Order filled exactly at: ${actual_fill_price}")
    print(f"Setting 50% profit exit target at: ${target_price}")

    # 4. Place the Take-Profit Limit Order
    # Using GTC (Good 'Til Canceled) so it remains active across multiple trading days
    exit_request = LimitOrderRequest(
        symbol=filled_order.symbol,
        qty=1,
        side=OrderSide.SELL,
        limit_price=target_price,
        time_in_force=TimeInForce.GTC
    )

    exit_order = trade_client.submit_order(exit_request)
    print("Take-profit limit order successfully placed and waiting!")

def get_all_option_positions(symbol):
    # 1. Fetch ALL currently open positions in your account
    all_positions = trade_client.get_all_positions()

    # 2. Filter the list for QQQ options
    # We check that the asset is an option, and the OCC symbol starts with "QQQ"
    qqq_option_positions = [
        position for position in all_positions
        if position.asset_class == AssetClass.US_OPTION and position.symbol.startswith("QQQ")
    ]

    # 3. Display the results

    if qqq_option_positions:
        print(f"Found {len(qqq_option_positions)} active QQQ option position(s):")

        for pos in qqq_option_positions:
            # Market value is returned as a string, so we convert to float for formatting
            market_value = float(pos.market_value)
            print(f"Contract: {pos.symbol} | Qty: {pos.qty} | Side: {pos.side.name} | Value: ${market_value:.2f}")
    else:
        print("No active QQQ option positions found in the account.")

    return qqq_option_positions

"""# QQQ LEAP execution"""

underlying_symbol = "QQQ"

if (get_all_option_positions(underlying_symbol)):
  print("Already in QQQ. Not entering new position")
else:
  selected_contract = select_high_interest_call_leap(underlying_symbol)
  place_order_with_exit_at_50pct_profit(selected_contract)
